config/routes.rb
Rails.application.routes.draw do
  Rails.application.routes.default_url_options[:host] = "localhost:3000"
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'reviews/autocomplete_review_food_name'
  resources :reviews
  root 'reviews#index'

  get 'reviews/show/:id' => 'reviews#show'

  get 'stores/info/:id' => 'reviews#infostore'

  # post 'comment/create' => 'comment#create'

  post 'reviews/:id/create-book-mark' => 'reviews#create_book_mark', as: 'create-bookmark'
  delete 'reviews/:id/delete-bookmark' => 'reviews#delete_bookmark', as: 'delete-bookmark'
  resources :book_marks
  # thach-nguyen
  get 'search' => 'reviews#search'
  post 'reviews/searchAction' => 'reviews#searchAction'
  post 'reviews/commentaction' => 'reviews#commentaction'
  post 'reviews/likeaction' => 'reviews#likeaction'
  post 'reviews/deleteCommentAct' => 'reviews#deleteCommentAct'
  post 'reviews/editCommentAct' => 'reviews#editCommentAct'
  post 'reviews/change' => 'reviews#change'
  post 'reviews/deleteReview' => 'reviews#deleteReview'
  # post 'comment/replyaction' => 'comment#replyaction'
  post 'reviews/replyaction' => 'reviews#replyaction'
  post 'reviews/deleteReplyAct' => 'reviews#deleteReplyAct'
  post 'reviews/editReplyAct' => 'reviews#editReplyAct'

  devise_for :users, :controllers => {:registrations => "users", :passwords => "passwords"}
  devise_scope :user do
    get 'users/:id', to: 'users#show', as: 'user'
    # post 'users/change' => 'users#change'
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  # autocomplete :review, :food_name, :full => true
  before_action :set_review, only: [:show, :edit, :update, :destroy]
  skip_before_action :verify_authenticity_token

  def searchAction
    price = params[:price]
    price = BigDecimal.new(price + "0000")
    today = Date.today
    sort = params[:sort]
    location = params[:location]

    if sort == "date"
      sort = "created_at"
    end
    lastweek = (Time.now - 7.day)
    lastmonth = (Time.now - 30.day)
    search_text = params[:search_text].tr('"/', "")
    val = params[:value]
    type = params[:type]

    post = Review.joins("INNER JOIN stores ON stores.id = reviews.store_id")
    post = post.select("reviews.id, food_name, reviews.price, reviews.created_at, reviews.price, store_address, food_picture, title")

    if type == "radio"
      case val
      when "anytime"
        post = post.where('food_name LIKE ? AND reviews.price < ? ', "%#{search_text}%", price)
      when  "today"
        post = post.where('food_name LIKE ? AND reviews.created_at > ? AND reviews.price < ?', "%#{search_text}%", today, price)
      when "lastweek"
        post = post.where('food_name LIKE ? AND reviews.created_at >= ? AND reviews.created_at < ? AND reviews.price < ?', "%#{search_text}%", lastweek, today, price)
      when "lastmonth"
        post = post.where('food_name LIKE ? AND reviews.created_at >= ? AND reviews.created_at < ? AND reviews.price < ?', "%#{search_text}%", lastmonth, today, price)
      end

    elsif type == "checkbox"
      case val
      when "stores"
        post = 5
      when "post"
        post = 6
      end
    end


    if location != ""
      post = post.where('store_address LIKE ?', "%#{location}%")
    end

    if sort != "Sort By"
      if sort == "price asc"
        post = post.order("reviews.price asc")
      elsif sort == "price desc"
        post = post.order("reviews.price desc")
      else
        post = post.order(sort + "desc")
      end
    end

    res = {"res" => post}

    respond_to do |format|
     format.html
     format.js {}
     format.json {
        render json: res
     }
   end

  end

  def search
    @search_text = params[:search_text]
    @reviews = Review.joins("INNER JOIN stores ON stores.id = reviews.store_id")
    @reviews = @reviews.select("reviews.id, food_name, reviews.price, reviews.created_at, reviews.price, store_address, food_picture, title")
    @reviews = @reviews.where('food_name LIKE ?', "%#{@search_text}%").paginate(:page => params[:page], :per_page => 5)
    @count = @reviews.count
  end

  def autocomplete_review_food_name
    term = params[:term]
    food_name = params[:food_name]
    reviews = Review.where('food_name LIKE ?', "%#{term}%")
    render :json => reviews.map { |review| {:id => review.id, :label => review.food_name, :value => review.food_name, :url => review.food_picture, :title => review.title, :price => review.price} }
  end
  # GET /reviews
  # GET /reviews.json
  def index
    # User Will_Paginate gem
    # 5 review per page
    @review_love = Comment.select("review_id, count(emotion_type) as count_like").where("emotion_type = 1").group("review_id").order("count_like DESC")
    @count0 = @review_love[0].count_like
    @count1 = @review_love[1].count_like
    @count2 = @review_love[2].count_like
    @count3 = @review_love[3].count_like
    @rev0 = Review.find(@review_love[0].review_id)
    @rev1 = Review.find(@review_love[1].review_id)
    @rev2 = Review.find(@review_love[2].review_id)
    @rev3 = Review.find(@review_love[3].review_id)

    # --------------------------------
    # most recent reviews
    @arr = Array.new
    @review_all = Review.order("created_at DESC")
    @arr.push @review_all[0]
    @arr.push @review_all[1]
    @arr.push @review_all[2]
    @arr.push @review_all[3]

    # ---------------------------------
    #

    @review = Review.new
    @reviews = Review.paginate(:page => params[:page], :per_page => 5)

    # Count number of like and dislike
    if params[:review_name]
      @reviews = Review.name_like(params[:review_name]).paginate(:page => params[:page], :per_page => 5)
    else
      @reviews = Review.paginate(:page => params[:page], :per_page => 5)
    end

    @likes = {}
    @dislikes = {}
    @nums = {}
    index = 0
    @reviews.each do |review|
      dislike = 0
      like = 0
      num = 0
      review.comments.each do |comment|
        if comment.emotion_type == 1
          like = like + 1
        end

        if comment.emotion_type == 0
          dislike = dislike + 1
        end
        if comment.emotion_type == -2
          num = num + 1
        end
      end
      @nums[review.id] = num
      @likes[review.id] = like
      @dislikes[review.id] = dislike
    end

    # find something
    # @reviews1 = Review.find([1,2,3,4])
  end


  # Control like action in home page
  def likeaction
    emotion_type = params[:emotion_type]
    type = params[:type]
    reviewId = params[:review_id]
    review = Review.find(reviewId)
    comment = review.comments.where("emotion_type != -2").find_by(user_id: current_user.id)
    case params[:emotion_type]
    # 1 means user click like button
    # 0 means user click dislike button
    when "1"
      # type 1 means people click like else people unlike that
      if type == "1"
        if comment == nil
          newCom = review.comments.new
          newCom.user_id = current_user.id
          newCom.emotion_type = 1
          newCom.save
        else
          comment.emotion_type = 1
          comment.save
        end
      else
          comment.emotion_type = -1
          comment.save
      end
    when "0"
      if type == "1"
        if comment == nil
          newCom = review.comments.new
          newCom.user_id = current_user.id
          newCom.emotion_type = 0
          newCom.save
        else
          comment.emotion_type = 0
          comment.save
        end
      else
          comment.emotion_type = -1
          comment.save
      end
    end
  end

  def editCommentAct
    comment_id = params[:commentId]
    comment = params[:comment]
    target = Comment.find(comment_id)
    target.comment = comment
    target.save
  end

  def change

    target = User.find(current_user.id)
    name = params[:name]
    if name != ""
        target.name = name
    end

    email = params[:email]
    if email != ""
        target.email = email
    end

    address = params[:address]
    if address != ""
        target.address = address
    end

    birthday = params[:birthday]
    if birthday != ""
        target.birthday = birthday
    end

    gender = params[:gender]
    if gender != ""
        target.gender = gender
    end

    target.save()
    redirect_back(fallback_location: root_path)
  end

  def deleteCommentAct
    comment_id = params[:commentId]
    comment = Comment.find(comment_id)
    comment.delete
  end

  def deleteReview
    review_id = params[:reviewId]
    review = Review.find(review_id)
    review.destroy
  end

  # GET /reviews/1
  # GET /reviews/1.json
  def show
    @review = Review.find(params[:id])
    @user_of_review = User.find_by id:@review.user_id
    @review_love = Comment.select("review_id, count(emotion_type) as count_like").where("emotion_type = 1").group("review_id").order("count_like DESC")
    @count0 = @review_love[0].count_like
    @count1 = @review_love[1].count_like
    @count2 = @review_love[2].count_like
    @count3 = @review_love[3].count_like
    @rev0 = Review.find(@review_love[0].review_id)
    @rev1 = Review.find(@review_love[1].review_id)
    @rev2 = Review.find(@review_love[2].review_id)
    @rev3 = Review.find(@review_love[3].review_id)

  end

  def infostore
    @review = Review.find(params[:id])
    @store_of_review = Store.find_by id:@review.store_id
  end

  # GET /reviews/new
  def new
    @review = Review.new
  end

  def commentaction
    content = params[:content]
    review_id = params[:review_id]
    review = Review.find(review_id)
    newCom = review.comments.new
    newCom.user_id = current_user.id
    newCom.emotion_type = -2
    newCom.review_id = review_id
    newCom.comment = content
    newCom.save
  end

  # GET /reviews/1/edit
  def edit
  end

  # POST /reviews
  # POST /reviews.json
  def create
    @review = Review.new(review_params)
    @review.user_id = current_user.id

    respond_to do |format|
      if @review.save
        format.html { redirect_to @review, notice: 'Review was successfully created.' }
        format.json { render :show, status: :created, location: @review }
      else
        format.html { render :new }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reviews/1
  # PATCH/PUT /reviews/1.json
  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to @review, notice: 'Review was successfully updated.' }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review.destroy
    respond_to do |format|
      format.html { redirect_to reviews_url, notice: 'Review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def create_book_mark
    @bookmark = BookMark.new
    @bookmark.review_id = params[:id]
    @bookmark.user_id = current_user.id
    if @bookmark.save
      respond_to do |format|
        format.html {redirect_to root_path}
        format.js
      end
    end
  end

  def delete_bookmark
    @bookmark = BookMark.where(review_id: params[:id]).where(user_id: current_user.id).first
    if @bookmark.destroy
      respond_to do |format|
        format.html {redirect_to root_path}
        format.js
      end
    end
  end

  private

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_bar_chart.html.erb
<div class="graph-cont">
  <div class="bar bar1">
    <span style="float: right;color: grey;">6/10</span>
    <div style="height: 30px; width: 60%; background-color: #FFB2B2">
      Safety Rate
    </div>
  </div>
  <div class="bar bar1">
    <span style="float: right;color: grey;">7/10</span>
    <div style="height: 30px; width: 70%; background-color: #FFB2B2">
      Price Rate
    </div>
  </div>
  <div class="bar bar1">
    <span style="float: right;color: grey;">10/10</span>
    <div style="height: 30px; width: 100%; background-color: #FFB2B2">
      Delicious Rate
    </div>
  </div>
</div>

app/views/reviews/_book_mark.html.erb
<% if user_signed_in? %>
    <% if BookMark.where(review_id: review.id).where(user_id: current_user.id) == [] %>
        <div style = "float: right">
            <%= link_to create_bookmark_path(review.id), class: "btn btn-primary", remote: true, method: :post do %>
                <i class="far fa-thumbs-up"></i>Bookmark
            <% end %>                 
        </div>
    <% else %>
        <div style = "float: right">
            <%= link_to delete_bookmark_path(review.id), class: "btn btn-primary", remote: true, method: :delete do %>
                <i class="far fa-thumbs-down"></i>Unbookmark
            <% end %> 
        </div>
    <% end %>
<% end %>

app/views/reviews/_form.html.erb
<%= form_with(model: review, local: true) do |form| %>
  <div style="height: 100%">
    <div class="img-in-form">
      <div class="field">
        <%= image_tag("news/upload.png")%>
        <%= form.file_field :food_picture, id: :review_food_picture, class: "image_upload" %>
      </div>
      <div class="price-rate">
          <div style="border-top: orange solid 1px; padding-top: 10px;">
            <div class="taste_rate_container">
              <div class="col-md-5">
                <label>Taste rate: </label>
              </div>
              <div class="col-md-7">
                <label class="radio-rate">
                  <input type="radio" name="review[taste_rate]" value="1" />
                  <i class="far fa-star rate1"></i>
                </label>

                <label class="radio-rate">
                  <input type="radio" name="review[taste_rate]" value="2" />
                  <i class="far fa-star rate2"></i>
                </label>

                <label class="radio-rate">
                  <input type="radio" name="review[taste_rate]" value="3" />
                  <i class="far fa-star rate3"></i>
                </label>

                <label class="radio-rate">
                  <input type="radio" name="review[taste_rate]" value="4" />
                  <i class="far fa-star rate4"></i>
                </label>

                <label class="radio-rate">
                  <input type="radio" name="review[taste_rate]" value="5" />
                  <i class="far fa-star rate5"></i>
                </label>
              </div>
            </div>

            <div class="taste_rate_container">
              <div class="col-md-5">
                <label>Price rate: </label>
              </div>
              <div class="col-md-7">
                <label class="radio-rate">
                  <input type="radio" name="review[price_rate]" value="1" />
                  <i class="far fa-star rate1"></i>
                </label>

                <label class="radio-rate">
                  <input type="radio" name="review[price_rate]" value="2" />
                  <i class="far fa-star rate2"></i>
                </label>

                <label class="radio-rate">
                  <input type="radio" name="review[price_rate]" value="3" />
                  <i class="far fa-star rate3"></i>
                </label>

                <label class="radio-rate">
                  <input type="radio" name="review[price_rate]" value="4" />
                  <i class="far fa-star rate4"></i>
                </label>

                <label class="radio-rate">
                  <input type="radio" name="review[price_rate]" value="5" />
                  <i class="far fa-star rate5"></i>
                </label>
              </div>
            </div>

            <div class="taste_rate_container">
              <div class="col-md-5">
                <label>Safety rate: </label>
              </div>
              <div class="col-md-7">
                <label class="radio-rate">
                  <input type="radio" name="review[safety_rate]" value="1" />
                  <i class="far fa-star rate1"></i>
                </label>

                <label class="radio-rate">
                  <input type="radio" name="review[safety_rate]" value="2" />
                  <i class="far fa-star rate2"></i>
                </label>

                <label class="radio-rate">
                  <input type="radio" name="review[safety_rate]" value="3" />
                  <i class="far fa-star rate3"></i>
                </label>

                <label class="radio-rate">
                  <input type="radio" name="review[safety_rate]" value="4" />
                  <i class="far fa-star rate4"></i>
                </label>

                <label class="radio-rate">
                  <input type="radio" name="review[safety_rate]" value="5" />
                  <i class="far fa-star rate5"></i>
                </label>
              </div>
            </div>
          </div>
      </div>
    </div>

    <div class="basic-info-form" style="height: 100%">
      <div class="field" style="height: 100%;">
        <label>Store Name: </label>
        <select name="review[store_id]" style="float: right; margin-bottom: 10px;">
            <% Store.all.each do |store| %>
                <option value="<%= store.id %>"><%= store.store_name %></option>
            <% end %>
        </select>
        <div class="title-container">
          <%= form.text_field :title, id: :review_title, placeholder: "Post's title (E.g: Very good)", class: "title" %>
        </div>
        <div class="title-container">
          <%= form.text_field :food_name, id: :review_food_name, placeholder: "Food's name", class: "food-name" %>
        </div>
        <div style="height: 100%;">
          <%= form.text_area :post_content, id: :review_post_content, placeholder: "Post content", class: "content" %>
        </div>
      </div>
    </div>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/reviews/_modal.html.erb
<div id="myModal" class="modal">
  <!-- Modal content -->
  <div class="modal-content">
    <div style="background-color: #ededed; padding: 10px ;margin-bottom: 10px;width: 100%; text-align: right;border-bottom: black solid 1px;">
      <span style="float: left;">Write your review: </span>
      <span style="border-left: black black 1px" id="close">close</span>
    </div>
    <% if user_signed_in? %>
      <div class="form-review" style="padding: 10px;">
        <%= render 'form', review: @review %>
      </div>
    <% end %>
  </div>

</div>

app/views/reviews/create_book_mark.js.erb
$('.bookmarks-<%= @bookmark.review.id %>').html('<%= j render "book_mark", review: @bookmark.review %>');

app/views/reviews/delete_bookmark.js.erb
$('.bookmarks-<%= @bookmark.review.id %>').html('<%= j render "book_mark", review: @bookmark.review %>');

app/views/reviews/edit.html.erb
<h1>Editing Review</h1>

<%= render 'form', review: @review %>

<%= link_to 'Show', @review %> |
<%= link_to 'Back', reviews_path %>

app/views/reviews/infostore.html.erb
<section class="single">
			<div class="container">
				<div class="row">
					<div class="col-md-4 sidebar" id="sidebar">
						<aside>
							<div class="aside-body">
								<figure class="ads">
									<%= image_tag("ad.png")%>
									<figcaption>Advertisement</figcaption>
								</figure>
							</div>
						</aside>
						<aside>
							<h1 class="aside-title">Bài viết về <%= @review.store.store_name%></h1>
							<div class="aside-body">
								<% @store_of_review.reviews.each do |review| %>
								<article class="article-mini">
									<div class="inner">
										<figure>
											<a href="/reviews/show/<%= review.id %>">
												<%= image_tag("news/buffet.jpg")%>
											</a>
										</figure>
										<div class="padding">
											<h1><a href="/reviews/show/<%= review.id %>"><%= review.title%></a></h1>
											<div class="detail">
												<div class="category"><a href="category.html"><%= review.created_at %></a></div>
												<div class="time"></div>
											</div>
										</div>
									</div>
								</article>
								<% end %>

							</div>
						</aside>
					</div>
					<div class="col-md-8">
						<article class="article main-article">
							<header>

								<h1><%= @review.store.store_name %></h1>
								<ul class="details">
									<li>thông tin chi tiết</li>
									<!-- <li>By <%= @review.user.name %></li> -->
								</ul>
							</header>
							<div class="main">
								<p>Tên nhà hàng: <%= @review.store.store_name %></p>
                <p>Địa chỉ: <%= @review.store.store_address %></p>
                <p>Giờ mở cửa: <%= @review.store.open_time %> h</p>
                <p>Giá cả: <%= @review.store.price %> đồng</p>
								<p>Số điện thoại: <%= @review.store.phone %></p>
							</div>

						</article>
						<div class="sharing">
						</div>

						<!-- <div class="line thin"></div>
						<div class="comments">
							<h2 class="title">Bình luận <a href="#">Write a Response</a></h2> -->



						<!-- <div class="comment-list">

							<% @review.comments.each do |comment| %>
								<div class="item">
									<div class="user">
										<figure>
											<%= image_tag("n.png")%>
										</figure>
										<div class="details">
											<h5 class="name"><%= comment.user.name%></h5>
											<div class="time"><%= comment.created_at%></div>
											<div class="description">
												<%= comment.comment%>
											</div>
											<footer>
												<a href="#">Reply</a>
											</footer>

										</div>
									</div>
								</div>
             　              <% end %>

						</div>

						 <%= form_for :comment, url: '/comment/create', :remote => true do |f| %>
								<%= f.hidden_field :review_id, { :value => @review.id}%>
								<%= f.hidden_field :emotion_type, { :value => 1} %>
								<%= f.text_area :comment, class: 'form-control', placeholder: 'Nội dung bình luận' %>
								<br>
								<%= f.submit 'Gửi bình luận'%>
						 <% end %>


						</div> -->
					</div>
				</div>
			</div>
</section>

app/views/reviews/new.html.erb
<section class="home review-list">
  <div class="container">
    <div class="row">
      <!-- Left site -->
      <div style="height: 500px; width: 100%;" class="col-md-8 col-md-offset-2 col-sm-12 col-xs-12">
        <% if @review.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

            <ul>
            <% @review.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>
      </div>
  </div>
</section>

app/views/reviews/search.html.erb
<section class="search">
  <div class="container">
    <div class="row">
      <div class="col-md-3">
        <aside>
          <h2 class="aside-title">Filter</h2>
          <input type="text" id="hidden_test_id" value="anytime" name="hidden_test" style="display: none;">
          <div class="aside-body">
            <form class="checkbox-group">
              <div class="group-title">Location</div>
              <div class="form-group">
                <input id="location" type="text" style="width: 100%;" name="date">
              </div>
              <div style="width: 100%" class="group-title">Price
                  <span style="float: right;font-weight: 300;"><span id="demo"></span> VND</span>
              </div>
              <div class="form-group">
                <div class="slidecontainer">
                  <input type="range" min="1" max="100" value="100" class="slider" id="myRange">
                </div>
              </div>
              <div class="group-title">Date</div>
              <div class="form-group">
                <label><input type="radio" name="date" value="anytime" checked> Anytime</label>
              </div>
              <div class="form-group">
                <label><input type="radio" id="today" value="today" name="date"> Today</label>
              </div>
              <div class="form-group">
                <label><input type="radio" value="lastweek" name="date"> Last Week</label>
              </div>
              <div class="form-group">
                <label><input type="radio" value="lastmonth" name="date"> Last Month</label>
              </div>
              <br>

            </form>
          </div>
        </aside>
      </div>
      <div class="col-md-9">
        <div class="nav-tabs-group">
          <ul class="nav-tabs-list">
            <li class="active"><a href="#">All</a></li>
          </ul>
          <div class="nav-tabs-right">
            <select id="sort" class="form-control">
              <option>Sort By</option>
              <option>price desc</option>
              <option>price asc</option>
              <option>date</option>
            </select>
          </div>
        </div>
        <div class="search-result">
          Search results for keyword <span id="search_text">"<%= @search_text %>"</span> found in <%= @count %> posts.
        </div>
        <div class="row search_content">

          <% @reviews.each do |review| %>
            <article class="col-md-12 article-list">
              <div class="inner">
                <figure>
                  <a href="reviews/show/<%= review.id %>">
                    <%= image_tag(review.food_picture)%>
                  </a>
                </figure>
                <div class="details">
                  <div class="detail">
                    <time><%= review.created_at %></time>
                  </div>
                  <h1><a href="reviews/show/<%= review.id %>"> <%= review.title %> </a></h1>
                  <p style="font-weight: bold;">
                  <%= review.store_address %>
                  </p>
                  <p>
                  <%= review.food_name %> - <%= review.price %> VND
                  </p>
                  <p>
                  Donec consequat, arcu at ultrices sodales, quam erat aliquet diam, sit amet interdum libero nunc accumsan nisi.
                  </p>
                  <footer>
                    <a class="btn btn-primary more" href="reviews/show/<%= review.id %>">
                      <div>More</div>
                      <div><i class="ion-ios-arrow-thin-right"></i></div>
                    </a>
                  </footer>
                </div>
              </div>
            </article>
          <% end %>
          <div class="col-md-12 text-center pagination">
            <%= will_paginate @users %>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>