config/routes.rb
Rails.application.routes.draw do
  Rails.application.routes.default_url_options[:host] = "localhost:3000"
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'reviews/autocomplete_review_food_name'
  resources :reviews
  root 'reviews#index'

  get 'reviews/show/:id' => 'reviews#show'

  get 'stores/info/:id' => 'reviews#infostore'

  # post 'comment/create' => 'comment#create'

  post 'reviews/:id/create-book-mark' => 'reviews#create_book_mark', as: 'create-bookmark'
  delete 'reviews/:id/delete-bookmark' => 'reviews#delete_bookmark', as: 'delete-bookmark'
  resources :book_marks
  # thach-nguyen
  get 'search' => 'reviews#search'
  post 'reviews/searchAction' => 'reviews#searchAction'
  post 'reviews/commentaction' => 'reviews#commentaction'
  post 'reviews/likeaction' => 'reviews#likeaction'
  post 'reviews/deleteCommentAct' => 'reviews#deleteCommentAct'
  post 'reviews/editCommentAct' => 'reviews#editCommentAct'
  post 'reviews/change' => 'reviews#change'
  post 'reviews/deleteReview' => 'reviews#deleteReview'
  # post 'comment/replyaction' => 'comment#replyaction'
  post 'reviews/replyaction' => 'reviews#replyaction'
  post 'reviews/deleteReplyAct' => 'reviews#deleteReplyAct'
  post 'reviews/editReplyAct' => 'reviews#editReplyAct'

  devise_for :users, :controllers => {:registrations => "users", :passwords => "passwords"}
  devise_scope :user do
    get 'users/:id', to: 'users#show', as: 'user'
    # post 'users/change' => 'users#change'
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="copyright">
          COPYRIGHT &copy; nohope. ALL RIGHT RESERVED.
        </div>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="primary">
      <div class="firstbar">
        <div class="container">
          <div class="row">
            <div class="col-md-3 col-sm-12">
              <div class="brand">
                <%= link_to root_path do %>
                  <%= image_tag("logo.png")%>
                <% end %>
              </div>
            </div>

            <!--- Search engine -->
            <div class="col-md-6 col-sm-12">

            </div>
            <%= render "layouts/login" %>
          </div>
        </div>
      </div>
    <% unless current_page?(new_user_session_path) || current_page?(new_user_registration_path)  %>
    <div style="background-color: #384049; padding: 30px">
      <div class="container">
        <div class="row"">
          <div class="col-md-2 col-sm-12">
          </div>

          <!-- Search engine -->
            <%= render "layouts/search" %>
          <div class="col-md-2 col-sm-12">
        </div>

        </div>
      </div>
    </div>
    <% end %>
</header>

app/views/layouts/_login.html.erb
<div class="col-md-3 col-sm-12 text-right login-menu">
  <ul class="nav-list nav-icons">
    <li class="for-tablet nav-title"><a>Menu</a></li>
    <% if user_signed_in? %>
      <li class="dropdown magz-dropdown">
        <div class="user_image">
          <%= image_tag("avatar.png", :id => "user_image_img")%>
        </div>
        <a id="user_name" href="#">Hi <%= current_user.name %> <i style="float: right;" class="ion-ios-arrow-right"></i>
        </a>
        <ul class="dropdown-menu">
          <li>
            <%= link_to user_path(1) do%>
              <i class="icon ion-person">
              </i> My Account
            <% end %>
          </li>
          <li>
            <%= link_to edit_user_registration_path do %>
              <i class="icon ion-settings"></i>Settings
            <% end %>
          </li>
          <% if current_user.is_admin %>
							<li>
                <%= link_to rails_admin.dashboard_path do%>
                  <i class="icon ion-person"></i>Admin Page
                <% end %>
              </li>
					<% end %>
          <li id="li_review" style="cursor: pointer;">
            <a>
              <i class="icon ion-chatbox"></i>Review
            </a>
          </li>
          <li>
            <%= link_to book_marks_path do %>
              <i class="icon ion-star"></i>Bookmark
            <% end %>
          </li>
          <li class="divider"></li>
          <li>
            <%= link_to destroy_user_session_path, method: :delete do %>
              <i class="icon ion-log-out"></i> Logout
            <% end %>
          </li>
        </ul>
      </li>
    <% else %>
      <li class="for-tablet"><a href="login.html">Login</a></li>
      <li class="for-tablet"><a href="register.html">Register</a></li>
      <li>
        <%= link_to new_user_registration_path do %>
          <i class="ion-person-add"></i><div>Register</div>
        <% end %>
      </li>
      <li>
        <%= link_to new_user_session_path do %>
          <i class="ion-person"></i><div>Login</div>
        <% end %>
      </li>
    <% end %>
  </ul>
</div>

app/views/layouts/_menu.html.erb
<nav class="menu">
        <div class="container">
          <div class="brand">
            <a href="#">
              <img src="images/logo.png" alt="Magz Logo">
            </a>
          </div>
          <div class="mobile-toggle">
            <a href="#" data-toggle="menu" data-target="#menu-list"><i class="ion-navicon-round"></i></a>
          </div>
          <div class="mobile-toggle">
            <a href="#" data-toggle="sidebar" data-target="#sidebar"><i class="ion-ios-arrow-left"></i></a>
          </div>
          <div id="menu-list">
            <ul class="nav-list">
              <li class="for-tablet nav-title"><a>Menu</a></li>
              <li class="for-tablet"><a href="login.html">Login</a></li>
              <li class="for-tablet"><a href="register.html">Register</a></li>
              <li><a href="category.html">Standard</a></li>
              <li class="dropdown magz-dropdown">
                <a href="category.html">Pages <i class="ion-ios-arrow-right"></i></a>
                <ul class="dropdown-menu">
                  <li><a href="index.html">Home</a></li>
                  <li class="dropdown magz-dropdown">
                    <a href="#">Authentication <i class="ion-ios-arrow-right"></i></a>
                    <ul class="dropdown-menu">
                      <li><a href="login.html">Login</a></li>
                      <li><a href="register.html">Register</a></li>
                      <li><%= link_to("Forgot Password", new_user_password_path, id:"forget-password", class:"forget-password") %></li>
                    </ul>
                  </li>
                  <li><a href="contact.html">Contact</a></li>
                  <% if user_signed_in? %>
                    <% if current_user.is_admin %>
                      <li><%= link_to "Admin Page", rails_admin.dashboard_path %></li>
                    <% end %>
                  <% end %>
                </ul>
              </li>

              <% if user_signed_in? %>
                <li class="dropdown magz-dropdown">
                  <a href="#">Account Setting <i class="ion-ios-arrow-right"></i>
                  </a>
                  <ul class="dropdown-menu">
                    <li>
                      <%= link_to user_path(1) do%>
                        <i class="icon ion-person">
                        </i> My Account
                      <% end %>
                    </li>
                    <li>
                      <%= link_to edit_user_registration_path do %>
                        <i class="icon ion-settings"></i>Settings
                      <% end %>
                    </li>
                    <li class="divider"></li>
                    <li>
                      <%= link_to destroy_user_session_path, method: :delete do %>
                        <i class="icon ion-log-out"></i> Logout
                      <% end %>
                    </li>
                  </ul>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>

app/views/layouts/_modal.html.erb
<div id="myModal" class="modal">
  <!-- Modal content -->
  <div class="modal-content">
    <div style="background-color: #ededed; padding: 10px ;margin-bottom: 10px;width: 100%; text-align: right;border-bottom: black solid 1px;">
      <span style="float: left;">Write your review: </span>
      <span style="border-left: black black 1px" id="close">close</span>
    </div>
    <% if user_signed_in? %>
      <div class="form-review" style="padding: 10px;">
        <%= render 'reviews/form', review: @review %>
      </div>
    <% end %>
  </div>

</div>

app/views/layouts/_search.html.erb
<div class="col-xs-6 col-md-12 sidebar" id="sidebar">
  <div class = "row">
    <div class = "col-md-6 col-md-offset-2">
      <%= form_tag("search", method: "get") do %>
        <!-- text field tag=action,args,identifier,placeholdertext... -->
        <%#= text_field_tag :search, params[:search], placeholder: "namesearch", type: "search", data: {autocomplete: reviews_autocomplete_review_food_name_path} %>
        <input name="search_text" type="text" placeholder="Type food name or restaurant's name" id="searchbar" class="search-query search_fix">
      </div>
      <div class = "col-md-2" >
        <%= submit_tag "Search"%>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Itnihon3Project</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge, chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <meta name="description" content="Magz is a HTML5 & CSS3 magazine template is based on Bootstrap 3.">
    <meta name="author" content="Kodinger">
    <meta name="keyword" content="magz, html5, css3, template, magazine template">
    <!-- Shareable -->
    <meta property="og:title" content="HTML5 & CSS3 magazine template is based on Bootstrap 3" />
    <meta property="og:type" content="article" />
    <meta property="og:url" content="http://github.com/nauvalazhar/Magz" />
    <meta property="og:image" content="https://raw.githubusercontent.com/nauvalazhar/Magz/master/images/preview.png" />
    <title>Magz &mdash; Responsive HTML5 &amp; CSS3 Magazine Template</title>
    <!-- Bootstrap -->
    <%= stylesheet_link_tag "/scripts/bootstrap/bootstrap.min.css" %>
    <!-- IonIcons -->
    <%= stylesheet_link_tag "/scripts/ionicons/css/ionicons.min.css" %>
    <!-- Toast -->
    <%= stylesheet_link_tag "/scripts/toast/jquery.toast.min.css" %>
    <!-- OwlCarousel -->
    <%= stylesheet_link_tag "/scripts/owlcarousel/dist/assets/owl.carousel.min.css" %>

    <%= stylesheet_link_tag "/scripts/owlcarousel/dist/assets/owl.theme.default.min.css" %>
    <!-- Magnific Popup -->
    <%= stylesheet_link_tag "/scripts/magnific-popup/dist/magnific-popup.css" %>
    <%= stylesheet_link_tag "/scripts/sweetalert/dist/sweetalert.css" %>


    <!-- Custom style -->
    <%= stylesheet_link_tag "/css/jquery-ui.min.css" %>

    <%= stylesheet_link_tag "/fontawesome/css/all.css" %>

    <%= stylesheet_link_tag "/scripts/icheck/skins/all.css" %>

    <%= stylesheet_link_tag "/css/style.css" %>
    <%= stylesheet_link_tag "/css/skins/all.css" %>
    <%= stylesheet_link_tag "/css/demo.css" %>
  </head>

  <body class="skin-orange">


    <%= render "layouts/modal" %>

    <%= render "layouts/header" %>

    <!-- content -->
    <%= yield %>

    <!-- Start footer -->

    <%= render "layouts/footer" %>
    <!-- End Footer -->

    <!-- JS -->
    <%= javascript_include_tag '/js/jquery.js' %>
    <%= javascript_include_tag '/js/jquery.migrate.js' %>
    <%= javascript_include_tag '/scripts/bootstrap/bootstrap.min.js' %>
    <script>var $target_end=$(".best-of-the-week");</script>
    <%= javascript_include_tag '/scripts/jquery-number/jquery.number.min.js' %>
    <%= javascript_include_tag '/scripts/owlcarousel/dist/owl.carousel.min.js' %>
    <%= javascript_include_tag '/scripts/magnific-popup/dist/jquery.magnific-popup.min.js' %>
    <%= javascript_include_tag '/scripts/easescroll/jquery.easeScroll.js' %>
    <%= javascript_include_tag '/scripts/sweetalert/dist/sweetalert.min.js' %>
    <%= javascript_include_tag '/scripts/toast/jquery.toast.min.js' %>
    <%= javascript_include_tag '/scripts/icheck/icheck.min.js' %>
    <%= javascript_include_tag '/js/jquery-ui.min.js' %>
    <script>$("input").iCheck({
      checkboxClass: 'icheckbox_square-red',
      radioClass: 'iradio_square-red',
      cursor: true
		});</script>
    <%= javascript_include_tag '/js/e-magz.js' %>
  </body>
</html>